import Script from "next/script";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      {/* <Script src='https://identity.netlify.com/v1/netlify-identity-widget.js' async /> */}
      <body>{children}</body>
    </html>
  );
}
